### ISSUE TITLE
大佬有没有对应的前端项目

### ISSUE THREAD

**Issue by mrgu1609** [town-coding/go-admin#1]
如题哈，
想学习学习

**Comment by town-coding** [comment]
有的，这个其实就是一个开源项目，我对后端部分的学习，gin-vue-admin这是源项目。你是学生吗？

Jelly ***@***.***> 于 2024年11月6日周三 19:03写道：

**Comment by wangx-wx** [comment]
> 如题哈， 想学习学习

有的，这个其实就是一个开源项目，我对后端部分的学习，gin-vue-admin这是源项目，我也是一位初学者
